// Recibir productos

export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT'

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
    "MENU_CHANGE_HAS_SUB_ITEM_STATUS";


//mio
export const PRODUCTS_MEDIATOR_FETCH = 'PRODUCTS_MEDIATOR_FETCH,'
export const PRODUCTS_MEDIATOR_FETCH_SUCCESS = 'PRODUCTS_MEDIATOR_FETCH_SUCCESS,'
export const PRODUCTS_MEDIATOR_FETCH_ERROR = 'PRODUCTS_MEDIATOR_FETCH_ERROR'


// settings

export const DEFAULT_SETTINGS = 'DEFAULT_SETTINGS'