// Recibir productos

export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT'

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
    "MENU_CHANGE_HAS_SUB_ITEM_STATUS";


//mio
export const PRODUCTS_MEDIATOR_FETCH = 'PRODUCTS_MEDIATOR_FETCH,'
export const PRODUCTS_MEDIATOR_FETCH_SUCCESS = 'PRODUCTS_MEDIATOR_FETCH_SUCCESS,'
export const PRODUCTS_MEDIATOR_FETCH_ERROR = 'PRODUCTS_MEDIATOR_FETCH_ERROR'


// settings

export const DEFAULT_SETTINGS = 'DEFAULT_SETTINGS';


// Cart

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREMENT_QTY = 'INCREMENT_QTY';
export const DECREMENT_QTY = 'DECREMENT_QTY';



export const FIREBASE_LOGIN = 'FIREBASE_LOGIN';
export const FIREBASE_LOGIN_SUCCESS = 'FIREBASE_LOGIN_SUCCESS';
export const FIREBASE_LOGIN_ERROR = 'FIREBASE_LOGIN_ERROR';
export const FIREBASE_LOGOUT = 'FIREBASE_LOGOUT';
export const FIREBASE_LOGOUT_SUCCESS = 'FIREBASE_LOGOUT_SUCCESS';
export const FIREBASE_RECOVERY_PASSWORD = 'FIREBASE_RECOVERY_PASSWORD';
export const FIREBASE_CHANGE_PASSWORD = 'FIREBASE_CHANGE_PASSWORD';
export const FIREBASE_REGISTER_USER_SUCCESS = 'FIREBASE_REGISTER_USER_SUCCESS';
export const FIREBASE_REGISTER_USER_INIT = 'FIREBASE_REGISTER_USER_INIT';
export const FIREBASE_CHANGE_EMAIL = 'FIREBASE_CHANGE_EMAIL';

// Orders
export const PLACE_AN_ORDER = 'PLACE_AN_ORDER';
export const PLACE_AN_ORDER_SUCCES = 'PLACE_AN_ORDER_SUCCES';
export const PLACE_AN_ORDER_ERROR = 'PLACE_AN_ORDER_ERROR'